cxx_library(
    name = "Mutable",
    header_namespace = "sharp/Mutable",
    exported_headers = [
        "Mutable.pre.hpp",
        "Mutable.hpp",
    ],
    deps = [
        "//Traits:Traits",
    ],
    visibility = [
        "PUBLIC",
    ],

    tests = [
        "//Mutable/test:test",
    ],
)
