cxx_library(
    name = "LessPtr",
    header_namespace = "sharp/LessPtr",
    headers = [
        "LessPtr.hpp",
    ],
    exported_headers = [
        "LessPtr.hpp",
    ],
    visibility = ["PUBLIC"],
)
