cxx_library(
    name = "Singleton",
    header_namespace = "sharp/Singleton",
    deps = [
        "//Tags:Tags",
        "//Concurrent:Concurrent",
        "//Threads:Threads",
    ],
    srcs = [
        "Singleton.cpp",
    ],
    headers = [
        "Singleton.hpp",
        "Singleton.ipp",
    ],
    exported_headers = [
        "Singleton.ipp",
        "Singleton.hpp",
    ],
    visibility = [
        "PUBLIC",
    ],


    tests = [
        "//Singleton/test:test",
    ],
)
