cxx_library(
    name = "Overload",
    header_namespace = "sharp/Overload",
    exported_headers = [
        "Overload.hpp",
        "Overload.ipp",
    ],
    visibility = [
        "PUBLIC",
    ],
    deps = [
        "//Traits:Traits",
    ],

    tests = [
        "//Overload/test:test",
    ],
)
