cxx_library(
    name = "Range",
    header_namespace = "sharp/Range",
    headers = [
        "Range.hpp",
        "Range.ipp",
    ],
    exported_headers = [
        "Range.hpp",
        "Range.ipp",
    ],
    visibility = [
        "PUBLIC",
    ],

    tests = [
        "//Range/test:test",
    ],
)
