cxx_library(
    name = "LockedData",
    deps = [
        "//Tags:Tags",
    ],

    headers = [
        "LockedData.hpp",
        "LockedData.ipp",
    ],
    exported_headers = [
        "LockedData.ipp",
        "LockedData.hpp",
    ],
    visibility = [
        "PUBLIC",
    ],
)
