cxx_library(
    name = "Threads",
    header_namespace = "sharp/Threads",

    srcs = glob([
        "**/*.cpp",
    ], excludes = [
        "**/test/*.cpp",
    ]),
    exported_headers = subdir_glob([
        ("", "**/*.hpp"),
        ("", "**/*.ipp"),
    ]),

    tests = [
        "//Threads/test:test",
    ],

    visibility = [
        "PUBLIC",
    ],
)
