cxx_library(
    name = "Concurrent",
    header_namespace = "sharp/Concurrent",
    deps = [
        "//Tags:Tags",
        "//Traits:Traits",
        "//Portability:Portability",
    ],
    exported_headers = [
        "Concurrent.ipp",
        "Concurrent.hpp",
    ],
    visibility = [
        "PUBLIC",
    ],

    tests = [
        "//Concurrent/test:test",
    ],
)
