cxx_library(
    name = "Traits",
    header_namespace = "sharp/Traits",
    exported_headers = [
        "Traits.hpp",
        "detail/IsInstantiationOf.hpp",
        "detail/IsCallable.hpp",
        "detail/IsOneOf.hpp",
        "detail/TypeLists.hpp",
        "detail/FunctionIntrospect.hpp",
        "detail/UnwrapPair.hpp",
        "detail/Algorithm.hpp",
        "detail/Functional.hpp",
        "detail/Utility.hpp",
    ],
    deps = [
        "//Tags:Tags",
    ],
    visibility = [
        "PUBLIC",
    ],

    tests = [
        "//Traits/test:test",
    ],
)
