cxx_library(
    name = "Traits",
    header_namespace = "sharp/Traits",
    exported_headers = [
        "Traits.hpp",
        "IsInstantiationOf.hpp",
        "IsCallable.hpp",
        "UnwrapPair.hpp",
    ],
    deps = [
        "//Tags:Tags",
    ],
    visibility = [
        "PUBLIC",
    ],

    tests = [
        "//Traits/test:test",
    ],
)
