cxx_library(
    name = "Portability",
    header_namespace = "sharp/Portability",
    exported_headers = [
        "cpp17.hpp",
        "detail/optional.hpp",
    ],
    visibility = [
        "PUBLIC",
    ],
)
