cxx_library(
    name = "LockedData",
    deps = [
        "//sharp/Tags:Tags",
    ],

    exported_headers = [
        "LockedData.ipp",
        "LockedData.hpp",
    ],
    visibility = [
        "PUBLIC",
    ],
)

cxx_binary(
    name = "test",
    srcs = [
        "test.cpp",
    ],
    deps = [
        ":LockedData",
    ],
)
